services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloverdash_backend
    env_file:
      - .env
    environment:
      # OpenAI Configuration
      OPENAI_MODEL: gpt-3.5-turbo
      OPENAI_TEMPERATURE: 0
      
      # API Configuration
      API_HOST: 0.0.0.0
      API_PORT: 8000
      API_TITLE: CloverdashBot Backend
      API_VERSION: 1.0.0
      
      # Security
      ALLOWED_ORIGINS: '["*"]'
      
      # Logging
      LOG_LEVEL: INFO
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"