services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloverdash_backend
    env_file:
      - .env
    environment:
      # OpenAI Configuration
      OPENAI_MODEL: gpt-3.5-turbo
      OPENAI_TEMPERATURE: 0
      
      # Database Configuration
      APP_DATABASE_URL: ${APP_DATABASE_URL}
      APP_DATABASE_HOST: ${APP_DATABASE_HOST}
      APP_DATABASE_PORT: ${APP_DATABASE_PORT}
      APP_DATABASE_USER: ${APP_DATABASE_USER}
      APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
      APP_DATABASE_NAME: ${APP_DATABASE_NAME}
      
      DATA_DATABASE_URL: ${DATA_DATABASE_URL}
      DATA_DATABASE_HOST: ${DATA_DATABASE_HOST}
      DATA_DATABASE_PORT: ${DATA_DATABASE_PORT}
      DATA_DATABASE_USER: ${DATA_DATABASE_USER}
      DATA_DATABASE_PASSWORD: ${DATA_DATABASE_PASSWORD}
      DATA_DATABASE_NAME: ${DATA_DATABASE_NAME}
      
      # API Configuration
      API_HOST: 0.0.0.0
      API_PORT: 8000
      API_TITLE: CloverdashBot Backend
      API_VERSION: 1.0.0
      
      # Security
      ALLOWED_ORIGINS: '["*"]'
      
      # Logging
      LOG_LEVEL: INFO
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app  # Uncomment for development only - causes rebuild issues in production
    restart: unless-stopped
    networks:
      - cloverdash-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  cloverdash-network:
    driver: bridge
    external: true