services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloverdash_telegram_bot
    env_file:
      - .env
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://host.docker.internal:8000}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" 