services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloverdash_telegram_bot
    env_file:
      - .env
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://cloverdash_backend:8000}
    restart: unless-stopped
    networks:
      - cloverdash-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  cloverdash-network:
    driver: bridge
    external: true 